syntax = "proto3";

package troyargonautsprotobuf;

enum ClimbLevel {
  CLIMB_NONE = 0;
  LEVEL_1 = 1;
  LEVEL_2 = 2;
  LEVEL_3 = 3;
}

enum TeleopPhase {
  TRANSITION_SHIFT = 0;
  SHIFT_1 = 1;
  SHIFT_2 = 2;
  SHIFT_3 = 3;
  SHIFT_4 = 4;
  END_GAME = 5;
}

enum PhaseActivity {
  SCORED = 0;
  PICKUP = 1;
  DEFENSE = 2;
  FED = 3;
}

enum PickupLocation {
  ALLIANCE_ZONE = 0;
  OUTPOST = 1;
  NEUTRAL_ZONE = 2;
  OPPONENT_AREA = 3;
}

message TeleopPhaseRecord {
  TeleopPhase phase = 1;
  PhaseActivity activity = 2;
  PickupLocation pickupLocation = 3;  // Only used when activity is PICKUP
  uint32 shotsMissed = 4;  // Only used when activity is SCORED
  uint32 shotsAttempted = 5;  // Only used when activity is SCORED
}

enum AutonPickupLocation {
  DEPOT = 0;
  OUTPOST = 1;
  NEUTRAL_ZONE = 2;
}

enum AutonPickupOutcome {
  FAILED = 0;
  ATTEMPTED = 1;
  SUCCESSFUL = 2;
}

message AutonPickupRecord {
  AutonPickupLocation location = 1;
  AutonPickupOutcome outcome = 2;
}

enum PreferredPath {
  NONE = 0;
  BUMP = 1;
  TRENCH = 2;
}

message MatchRecord {
  enum Alliance {
    R1 = 0;
    R2 = 1;
    R3 = 2;
    B1 = 3;
    B2 = 4;
    B3 = 5;
  }

  enum StartingPosition {
    P1 = 0;
    P2 = 1;
    P3 = 2;
    P4 = 3;
    P5 = 4;
  }

  string id = 1;

  // identifiers
  string team = 2;
  string match = 3;
  string scouter = 4;
  Alliance alliance = 17;
  StartingPosition startingPosition = 18;
  repeated TeleopPhaseRecord teleopPhases = 19;

  // prematch
  uint32 preloadedGameElements = 14;
  bool robotMovedInAuton = 20;
  repeated AutonPickupRecord autonPickups = 21;

  // scoring (main area)
  uint32 autonShotsMissed = 5;
  uint32 autonShotsAttempted = 6;
  uint32 teleopShotsMissed = 7;
  uint32 teleopShotsAttempted = 8;

  // endgame
  ClimbLevel climbLevel = 9;

  // capabilities
  bool canGoOverBump = 10;
  bool canGoUnderTrench = 11;
  bool canClimbLevel1Auton = 13;
  bool neutralZoneFeedingAuton = 15;
  bool neutralZoneFeedingTeleop = 16;

  // misc
  string notes = 12;
  PreferredPath preferredPath = 22;
}

message MatchRecords {
  repeated MatchRecord records = 1;
}

