syntax = "proto3";

package troyargonautsprotobuf;

enum ClimbLevel {
  CLIMB_NONE = 0;
  LEVEL_1 = 1;
  LEVEL_2 = 2;
  LEVEL_3 = 3;
}

message MatchRecord {
  string id = 1;

  // identifiers
  string team = 2;
  string match = 3;
  string scouter = 4;

  // scoring (main area)
  uint32 autonShotsAttempted = 5;
  uint32 autonShotsMade = 6;
  uint32 teleopShotsAttempted = 7;
  uint32 teleopShotsMade = 8;

  // endgame
  ClimbLevel climbLevel = 9;

  // capabilities
  bool canGoOverBump = 10;
  bool canGoUnderTrench = 11;
  bool canClimbLevel1Auton = 13;

  // misc
  string notes = 12;
}

message MatchRecords {
  repeated MatchRecord records = 1;
}

